# Based on macos.yml from {fmt}
# https://github.com/fmtlib/fmt/blob/master/.github/workflows/macos.yml

name: macos

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-15
    strategy:
      matrix:
        compiler: [AppleClang, LLVM-Clang-17, LLVM-Clang-18, LLVM-Clang-19, LLVM-Clang-20, LLVM-Clang-21]
        build_type: [Debug, Release]
        env:
          - CXXFLAGS: -Wall -Wextra -Wconversion -Wsign-conversion -pedantic -fno-omit-frame-pointer

        include:
          - compiler: AppleClang
            cxx: clang++
            install: |
              brew install ninja
          - compiler: LLVM-Clang-17
            cxx: $(brew --prefix llvm@17)/bin/clang++
            build_module: false
            install: |
              brew install llvm@17 ninja
          - compiler: LLVM-Clang-18
            cxx: $(brew --prefix llvm@18)/bin/clang++
            build_module: true
            install: |
              brew install llvm@18 ninja
          - compiler: LLVM-Clang-19
            cxx: $(brew --prefix llvm@19)/bin/clang++
            build_module: true
            install: |
              brew install llvm@19 ninja
          - compiler: LLVM-Clang-20
            cxx: $(brew --prefix llvm@20)/bin/clang++
            build_module: true
            install: |
              brew update
              brew install llvm@20 ninja
          - compiler: LLVM-Clang-21
            cxx: $(brew --prefix llvm@21)/bin/clang++
            ldflags: -L$(brew --prefix llvm@21)/lib/c++
            build_module: true
            install: |
              brew update
              brew install llvm@21 ninja


    steps:
    - uses: actions/checkout@master

    - name: Create Build Environment
      run: |
        ${{matrix.install}}

    - name: Configure
      run: |
        cmake -B build -GNinja \
              -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
              -DCMAKE_CXX_COMPILER=${{matrix.cxx}} \
              -DCMAKE_EXE_LINKER_FLAGS=${{matrix.ldflags}} \
              -DCMAKE_COMPILE_WARNING_AS_ERROR=On \
              -DCMAKE_LINK_WARNING_AS_ERROR=On \
              -DTCB_POINTER_BUILD_MODULE=${{matrix.build_module}}

    - name: Build
      run: cmake --build build --config ${{matrix.build_type}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{matrix.build_type}}
      env:
        CTEST_OUTPUT_ON_FAILURE: True
