name: Sanitizers

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sanitizer: [address, undefined]
        build_type: [Debug, Release]
        include:
          - cxx: g++-15
            install: |
              brew install gcc@15 ninja binutils
              brew link --force binutils

    steps:
      - uses: actions/checkout@master

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Create Build Environment
        run: |
          ${{matrix.install}}

      - name: Configure
        run: |
          cmake -B build -GNinja \
                -DCMAKE_CXX_COMPILER=${{matrix.cxx}} \
                -DCMAKE_CXX_EXTENSIONS=Off \
                -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
                -DCMAKE_CXX_FLAGS="-fsanitize=${{matrix.sanitizer}}" \
                -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=${{matrix.sanitizer}}" \
                $GITHUB_WORKSPACE

      - name: Build
        run: cmake --build build

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{matrix.build_type}}
        env:
          CTEST_OUTPUT_ON_FAILURE: True
