name: windows

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        platform: [x86, x64]
        build_type: [Debug, Release]
        env:
          - CXXFLAGS: /utf-8 /Zc:__cplusplus /Zc:throwingNew /Zc:inline /Zc:externConstexpr /Zc:templateScope /Zc:checkGwOdr /Zc:enumTypes /W4

    steps:
    - uses: actions/checkout@master
    - uses: seanmiddleditch/gha-setup-ninja@master
    - uses: TheMrMilchmann/setup-msvc-dev@v3
      with:
        arch: ${{matrix.platform}}

    - name: Configure
      shell: bash
      run: |
        cmake -B build -G Ninja \
              -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
              -DCMAKE_CXX_EXTENSIONS=Off \
              -DCMAKE_COMPILE_WARNING_AS_ERROR=On \
              -DCMAKE_LINK_WARNING_AS_ERROR=On \
              -DTCB_POINTER_BUILD_MODULE=On \

    - name: Build
      run: cmake --build build --config ${{matrix.build_type}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{matrix.build_type}} -V
      env:
        CTEST_OUTPUT_ON_FAILURE: True
